[package]
name = "horizon"
version = "0.1.0"
authors = ["Gregory Langlais <general@gregorylanglais.com>"]
edition = "2018"
description = "Horizon is a high performance Journal"
license = "MIT"

[dependencies]
capnp = "0.10.3"